hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - optimizing/config/lr_scheduler=glob(*)
  job:
    name: train
    chdir: null
    override_dirname: optimizing/config/lr_scheduler=glob(*)
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.2.0
    version_base: '1.2'
    cwd: /home/matej/projects/lumen-geoguesser
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/matej/projects/lumen-geoguesser/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      geo/crs: croatia
      model: resnext101_32x8d
      optimizing/config/lr_scheduler: exponential_lr
      optimizing/config/optimizer: adam
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
optimizing:
  config:
    optimizer:
      type: Adam
      kwargs:
        lr: 0.0001
    lr_scheduler: glob(optimizing/config/lr_scheduler/*)
    set_grads_none: true
model:
  type: resnext101_32x8d
  params: {}
  pretrained: true
  unfreeze_layers_num: all
geo:
  crs:
    local_crs: 3766
    country_iso2: hr
  global_crs: 4326
torchvision_version: pytorch/vision:v0.12.0
datamodule:
  image_size: 224
  csv_spacing: 0.7
  dataset_frac: 1
  train_frac: 0.9
  val_frac: 0.05
  test_frac: 0.05
  shuffle_dataset_before_splitting: false
  num_workers: 4
  drop_last: true
  batch_size: 8
  dataset_dirs:
  - /data/original
  - /data/external
trainer:
  log_every_n: 100
  max_epochs: 22
  lr: 2.0e-05
  lr_finetune: 2.0e-05
  finetuning_epoch_period: 5
  early_stopping_epoch_freq: 15
  weight_decay: 0
