# based on Luka Šimac's config

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.18.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

-   repo: local
    hooks:
      - id: poetry_check
        name: poetry check
        entry: poetry check
        language: system
        files: "pyproject.toml"
        pass_filenames: false

      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

      - id: bandit
        name: bandit
        entry: poetry run bandit -c pyproject.toml
        language: system
        types: [python]

      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry run mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        verbose: true
