accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 8
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: null
context_dict:
  accelerator: null
  accumulate_grad_batches: null
  amp_backend: native
  amp_level: null
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  batch_size: 8
  benchmark: false
  check_val_every_n_epoch: 1
  checkpoint_callback: null
  dataset_dir: &id001 !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - matej
  - projects
  - lumen-geoguesser
  - data
  - raw.ignoreme
  dataset_frac: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: null
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  flush_logs_every_n_steps: null
  gpus: null
  gradient_clip_algorithm: null
  gradient_clip_val: null
  image_size: 28
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 3
  limit_train_batches: 3
  limit_val_batches: 3
  log_every_n_steps: 1
  log_gpu_memory: null
  logger: true
  lr: 0.0001
  max_epochs: null
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  models: &id002
  - resnext101_32x8d
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 2
  output_report: &id003 !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - matej
  - projects
  - lumen-geoguesser
  - reports
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: null
  pretrained: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  quick: true
  reload_dataloaders_every_epoch: false
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  shuffle_before_splitting: false
  split_ratios: &id004
  - 0.6
  - 0.2
  - 0.2
  stochastic_weight_avg: false
  strategy: null
  sync_batchnorm: false
  terminate_on_nan: null
  tpu_cores: null
  track_grad_norm: -1
  trainer_checkpoint: null
  unfreeze_backbone_at_epoch: 4
  unfreeze_blocks: all
  val_check_interval: 1.0
  weight_decay: 1.0e-05
  weights_save_path: null
  weights_summary: top
  wokers_num: 4
dataset_dir: *id001
dataset_frac: 1
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
flush_logs_every_n_steps: null
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
image_size: 28
ipus: null
learning_rate: 0.0001
leave_last_n: all
limit_predict_batches: 1.0
limit_test_batches: 3
limit_train_batches: 3
limit_val_batches: 3
log_every_n_steps: 1
log_gpu_memory: null
logger: true
lr: 0.0001
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_name: resnext101_32x8d
models: *id002
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_classes: 4
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
output_report: *id003
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
pretrained: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
quick: true
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
shuffle_before_splitting: false
split_ratios: *id004
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
trainer_checkpoint: null
unfreeze_backbone_at_epoch: 4
unfreeze_blocks: all
val_check_interval: 1.0
weight_decay: 1.0e-05
weights_save_path: null
weights_summary: top
wokers_num: 4
