DEFAULT_IMAGE_SIZE = 64

"""DATASET"""
DEFAULT_DATASET_FRAC = 1
DEFAULT_TRAIN_SIZE = 0.8
DEFAULT_VAL_SIZE = 0.1
DEFAULT_TEST_SIZE = 0.1

"""TRAINING"""
DEAFULT_NUM_WORKERS = 4
DEAFULT_DROP_LAST = True
DEFAULT_BATCH_SIZE = 8
BATCH_PRINT_EVERY = 10
BATCH_VALIDATE_EVERY = 2000
DEFAULT_LR = 0.01
